<?php
/**
 * @category  Utiks
 * @package   Utiks_GpgCheckout
 * @copyright Copyright (c) 2015 utiks (http://www.utiks.com)
 */
?>
<p class="subtitle"><strong><?php echo (Mage::helper('utiks_gpgcheckout')->getStoreConfigByName('title') != '' ? Mage::helper('utiks_gpgcheckout')->getStoreConfigByName('title') : $this->escapeHtml($this->getMethod()->getTitle()));?></strong></p>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<dl class="payment-info">
    <?php foreach ($_specificInfo as $_label => $_value):?>
        <dt><?php echo $this->escapeHtml($_label)?></dt>
        <dd><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n"))?></dd>
    <?php endforeach; ?>
</dl>
<?php endif;?>
<div>
    <img src="<?php echo Mage::getBaseUrl('media')."gpgcheckout/gpgcheckout.png" ?>" />
</div>
<?php echo $this->getChildHtml()?>
